# Configuração para controlar a formatação do código
linter:
  rules:
    # Desabilitar regras específicas de formatação
    - prefer_single_quotes: false
    - prefer_expression_function_bodies: false

# Configuração do formatador
formatter:
  line_length: 300  # Aumentar o comprimento da linha
