name: front_leilaorv
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.3
  http: ^1.1.0
  convert: ^3.0.2
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  image_picker: ^1.0.4
  shared_preferences: ^2.5.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

